port: 4000
host: '0.0.0.0'
tracing: false
cookies:
  secret: 'mOzmz=r9*lF3bDg]^$aUSsUpvTv70[Fv'
corsConfig:
  credentials: true
  origin:
    - http://localhost:4200
    - https://manager-app-mrsupertop.vercel.app
redis:
  instance:
    username: 'default'
    password: vop1ZYiDOaCbWFhp9uWoaSX2FMtdv5gs
    port: 15427
    host: 'redis-15427.c293.eu-central-1-1.ec2.cloud.redislabs.com'
  namespaces:
    sessionData:
      prefix: 'sess'
      expires: 2592000 # 30 days
    registrationConfirmation:
      prefix: 'reg_conf'
      expires: 259200 # 3 days
    forgotPassword:
      prefix: 'forgot_pass'
      expires: 900 # 15 minutes
session:
  cookie:
    name: 'sess_id'
    httpOnly: true
    maxAge: 2592000 # 30 days
    secure: true
    sameSite: 'none'
    signed: true
emails:
  nodemailer:
    transporter:
      host: 'smtp.gmail.com'
      port: 465
      auth:
        user: 'manager.app.confirm@gmail.com'
        type: 'oauth2'
  gmail:
    client_id: '611226891059-f0e8pdfamgica50jlcpf86pjcr43ng0p.apps.googleusercontent.com'
    client_secret: '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'
    redirect_uri: 'https://developers.google.com/oauthplayground'
    refresh_token: '1//04RoNY3yurrObCgYIARAAGAQSNwF-L9IrH1G3IwHX4KCxx3unDH-Bebyab-jY9gdgQA1D4nUOrXO7GYhayZ0T8ztel18jvfNSGrY'
oauth:
  google:
    clientId: '611226891059-q4u6coip9jg6qkiat5midobpdu94mh8p.apps.googleusercontent.com'
    clientSecret: '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'
    redirect: 'https://manager-app-mrsupertop.vercel.app'
  github:
    clientId: '10915aed9a65bb6e508b'
    clientSecret: '14bed363739939f50c7034cad79d3190f47aee9b'
    redirect: 'https://manager-app-mrsupertop.vercel.app'
  discord:
    clientId: '963526836267151391'
    clientSecret: 'SaJVXiX10bFGay8arrWc9ys-rgdyXaKC'
    redirect: 'https://manager-app-mrsupertop.vercel.app'